name: lime
description: LIME Protocol for Dart/Flutter - A lightweight messaging library
version: 0.0.9
homepage: https://limeprotocol.org/
repository: https://github.com/takenet/lime-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.5
  simple_logger: ^1.9.0
  pretty_json: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

