name: lime
description: lime protocol
version: 0.0.1
homepage: https://limeprotocol.org/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.5
  simple_logger: ^1.9.0
  pretty_json: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

