name: Create Tag

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-gen-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jacopocarlini/action-autotag@2.0.4
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
